services:
  go-react-smallapp:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
  
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: go-react-small-app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
      - "5173:5173"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    command: sh -c 'npm install && npm run dev'

volumes:
  pgdata: