// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type Grade struct {
	ID        int32
	Name      string
	SubjectID int32
	Grade     int32
	CreatedAt sql.NullTime
}
